ALTER TABLE students ADD COLUMN IF NOT EXISTS guardian_relationship VARCHAR(80);
ALTER TABLE students ADD COLUMN IF NOT EXISTS guardian_document VARCHAR(30);
ALTER TABLE students ADD COLUMN IF NOT EXISTS guardian_contact VARCHAR(40);
ALTER TABLE students ADD COLUMN IF NOT EXISTS guardian_whatsapp VARCHAR(40);
ALTER TABLE students ADD COLUMN IF NOT EXISTS whatsapp_opt_in BOOLEAN NOT NULL DEFAULT TRUE;
